### ISSUE TITLE
Errors during running general_filter.py

### ISSUE THREAD

**Issue by jackieduckie** [adamewing/tebreak#17]
I run into this error when running `general_filter.py `as instructed. 
```2020-01-14 12:57:23,316 Filtered 7016f028-cc10-4264-b3f0-5056e53b3e1e: total consensus length < 300
Traceback (most recent call last):
  File "/home/dong.rn/home/StructuralVariantAnnotation/tebreak/tebreak/scripts/general_filter.py", line 540, in <module>
    main(args)
  File "/home/dong.rn/home/StructuralVariantAnnotation/tebreak/tebreak/scripts/general_filter.py", line 344, in main
    self_align = align(inslib[ins_id], refseq, minmatch=95)
  File "/home/dong.rn/home/StructuralVariantAnnotation/tebreak/tebreak/scripts/general_filter.py", line 64, in align
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/stornext/System/data/apps/python/python-3.7.0/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/stornext/System/data/apps/python/python-3.7.0/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'exonerate': 'exonerate'
```

I'm running python 3.7.0. Is there possibly something missing?

**Comment by jackieduckie** [comment]
Sorry I've solved it.
